export const SOURCE_FORM_HOOK_CONTENT = '@formily/devtools/hook.content'

export const CHANNEL_CONTENT_TO_BACKGROUND = 'CHANNEL_CONTENT_TO_BACKGROUND'

export const CHANNEL_DEVTOOLS_PANEL_TO_BACKGROUND =
  'CHANNEL_DEVTOOLS_PANEL_TO_BACKGROUND'

export const FORMILY_DEV_TOOLS_INSPECT_HOOK =
  '__FORMILY_DEV_TOOLS_INSPECT_HOOK__'
