name: Release Devtools
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: |
            - cwd: devtools/chrome-extension
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/
      - run: |
          node --version
          pnpm -v
          cd devtools/chrome-extension
          pnpm i
          pnpm run build
          pnpm run package
        env:
          # avoid core dump, see: https://github.com/parcel-bundler/parcel/issues/10081
          PARCEL_WORKER_BACKEND: process
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: formily-devtools
          path: devtools/chrome-extension/build/chrome-mv3-prod.zip
