name: Release Devtools
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: |
          node --version
          yarn -v
          yarn --ignore-engines
          cd devtools/chrome-extension
          yarn list --depth=0
          yarn run build
          yarn run package
        env:
          # avoid core dump, see: https://github.com/parcel-bundler/parcel/issues/10081
          PARCEL_WORKER_BACKEND: process
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: formily-devtools
          path: devtools/chrome-extension/build/chrome-mv3-prod.zip
